version: '3.8'
services:
  db:
    image: ghostvk/categories_app_db
    build: ./db
    container_name: categories_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '6543:5432'
    environment:
      POSTGRES_PASSWORD: cat123
      POSTGRES_USER: cat
      POSTGRES_DB: categories
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cat -d categories"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - db

  api:
    image: ghostvk/categories_app_app.dev
    build: 
      context: ./app
      dockerfile: Dockerfile.development
    container_name: categories_api
    volumes:
      - ./app:/usr/src/app
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      POSTGRES_PASSWORD: cat123
      POSTGRES_USER: cat
      POSTGRES_DB: categories
      POSTGRES_PORT: 5432 
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

networks:
  db:
    driver: bridge
